import {useEffect,useRef,useState} from 'react';
import type {Product} from '../always-on/data';
import {currentProfile,saveMeasurements,sizing,useConnectedProfile} from '../always-on/connection';
export default function VogueSizing({product}:{product:Product;size:string;onSize:(s:string)=>void}){
 const{identity}=useConnectedProfile();const[height,setHeight]=useState(identity?.height||172),[weight,setWeight]=useState(identity?.weight||65),[result,setResult]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);const controller=useRef<AbortController|null>(null);
 useEffect(()=>{if(identity){setHeight(identity.height);setWeight(identity.weight)}setResult('');setError('');controller.current?.abort();setBusy(false)},[product.id,identity?.id]);useEffect(()=>()=>controller.current?.abort(),[]);
 async function calculate(){setError('');setResult('');if(!Number.isFinite(height)||!Number.isFinite(weight)||height<100||height>230||weight<30||weight>250){setError('Enter a height from 100–230 cm and weight from 30–250 kg.');return}if(!identity){setError('Choose a model or add your photo to get a personal recommendation.');return}controller.current?.abort();const ac=new AbortController();controller.current=ac;setBusy(true);try{await saveMeasurements({...identity,height,weight});if(ac.signal.aborted)return;const person=currentProfile().identity;if(!person)throw Error('Your profile changed. Please choose your model or photo again.');const data=await sizing(product.garmentId||product.id,person,ac.signal);if(ac.signal.aborted)return;const recommendation=data.sizing?.size;if(!recommendation)throw Error('A calibrated recommendation is not available for this piece yet. Please use the retailer’s size guide.');setResult('Recommended size: '+recommendation)}catch(e){if(!ac.signal.aborted)setError(e instanceof Error?(/no size chart/i.test(e.message)?'Personal sizing is not available for this piece yet. Please check the retailer’s size guide.':e.message):'Your size could not be calculated. Please try again.')}finally{if(!ac.signal.aborted)setBusy(false)}}
 return <section className="partner-sim-sizing"><small>PERSONAL SIZE RECOMMENDATION</small><h2>Find your fit.</h2><p>Use your measurements to request a recommendation for {product.name} from SPREEAI. Final availability and sizing are confirmed by the retailer.</p><div><label>Height (cm)<input aria-label="Sizing height in centimeters" type="number" min="100" max="230" value={height} onChange={e=>setHeight(Number(e.target.value))}/></label><label>Weight (kg)<input aria-label="Sizing weight in kilograms" type="number" min="30" max="250" value={weight} onChange={e=>setWeight(Number(e.target.value))}/></label></div><button className="primary" disabled={busy||!identity} onClick={calculate}>{busy?'Finding your size…':'Find my size'}</button>{result&&<p role="status">{result}</p>}{error&&<p role="alert">{error}</p>}<p className="vogue-fine">Recommendations require calibrated garment measurements. If this piece is still being prepared, check its retailer size guide.</p><a className="vogue-outline" href={product.retailerUrl} target="_blank" rel="noreferrer">VIEW RETAILER SIZE GUIDE</a></section>
}
