import {useState} from 'react';
import type {RetailProduct} from './Retail';
type Guide={url:string;rows:(string|number)[][]};
const guides:Record<string,Guide>={
'Alice + Olivia':{url:'https://www.aliceandolivia.com/pages/global-size-guide',rows:[['0',31.5,25,34.5],['2',31.5,26,35.5],['4',33.5,27,36.6],['6',34.5,28,37.5],['8',35.5,29,38.5],['10',36.5,30,39.5],['12',38,31.5,41],['14',39.75,33.5,43]]},
'Cult Gaia':{url:'https://cultgaia.com/',rows:[['XS',33,25,36.5],['S',35,27.5,38.5],['M',36.5,29.5,41.5],['L',38,31.5,43.5],['XL',39.5,33.5,45.5]]},
'Sergio Hudson':{url:'https://sergiohudson.com/pages/sizing-chart',rows:[['0',33,25.75,35.5],['2',34,26.75,36.5],['4',35,27.75,37.5],['6',36,28.75,38.5],['8',37.5,30.25,40],['10',39,31.75,41.5],['12',40.5,33.25,43],['14',42,34.75,44.5],['16',43,36.25,46]]},
'Michael Kors':{url:'https://www.michaelkors.global/on/demandware.store/Sites-mk_anz-Site/en_AU/SizeGuide-Show?cid=womens-clothing',rows:[['XXS',31,24,33.5],['XS',33,26,35.5],['S',35,28,37.5],['M',37.5,30.5,40],['L',40.5,33.5,43],['XL',42,35,44.5],['XXL',43.5,36.5,46]]}};
export default function SizeGuide({product,onSize,onExplore}:{product:RetailProduct;onSize:(s:string)=>void;onExplore:()=>void}){const [unit,setUnit]=useState('in'),[measure,setMeasure]=useState<Record<string,string>>({}),[match,setMatch]=useState('');const guide=guides[product.source?.[0]||''];if(!guide)return <div className="retail-body-guide"><h3>{product.source?.[0]} size & fit</h3><p>Choose your size with the original retailer. Vogue’s edit does not publish a size chart for this piece.</p><p>SPREEAI sizing demonstrations are simulations and do not establish stock availability or a calibrated fit prediction.</p><a className="retail-official" href={product.retailerUrl} target="_blank" rel="noreferrer">View retailer sizing and product details</a></div>;function calculate(){const vals=['Bust','Waist','Hip'].map(k=>Number(measure[k])/(unit==='cm'?2.54:1));if(vals.some(x=>!Number.isFinite(x)||x<15||x>70)){setMatch('Enter valid bust, waist and hip measurements.');return}const row=guide.rows.filter(r=>product.sizes.includes(String(r[0]))).find(r=>vals.every((v,i)=>v<=Number(r[i+1])));if(!row){setMatch('Your measurements fall outside this published guide. Consult the brand for fit advice.');return}setMatch('Body-chart match: '+row[0]+'. Confirm against the garment’s cut and fabric.');onSize(String(row[0]))}return <div className="retail-body-guide"><div className="retail-guide-units"><button aria-pressed={unit==='in'} onClick={()=>setUnit('in')}>INCHES</button><button aria-pressed={unit==='cm'} onClick={()=>setUnit('cm')}>CENTIMETERS</button></div><table><thead><tr>{['Size','Bust','Waist','Hip'].map(s=><th key={s}>{s}</th>)}</tr></thead><tbody>{guide.rows.map(r=><tr key={String(r[0])}>{r.map((v,i)=><td key={i}>{i===0?v:unit==='cm'?Math.round(Number(v)*2.54*10)/10:v}</td>)}</tr>)}</tbody></table><p>Published brand body measurements. These are not garment dimensions or a calibrated SPREEAI prediction.</p><div className="retail-measurements">{['Bust','Waist','Hip'].map(k=><label key={k}>{k} ({unit})<input type="number" inputMode="decimal" min="1" value={measure[k]||''} onChange={e=>setMeasure(m=>({...m,[k]:e.target.value}))}/></label>)}</div><button className="retail-guide-match" onClick={calculate}>FIND MY CHART MATCH</button><p role="status">{match}</p><button className="retail-add" onClick={onExplore}>COMPARE SIZES ON YOU</button><a className="retail-official" href={guide.url} target="_blank" rel="noreferrer">View published brand size guide</a></div>}
