import {useTutorialsEnabled} from './tutorialPreference';
import {useState} from 'react';
import AutoVideo from './AutoVideo';
import featureVideos from './feature-videos.json';
type Lesson={video:string;poster:string;captions?:string;transcript:string};
const lessons=featureVideos as Record<string,Lesson>;
const notes:Record<string,[string,string,string]>={
 recommendations:['Personal recommendations','The brand’s curated edit appears on the selected shopper or Twin automatically.','Choose recommendation logic, eligible products, placement, and how your brand curates the edit.'],
 collection:['Shopping with Always On','Browse the garments as you would in any store. Hover to see a collection model, then open a piece to explore its gallery.','Choose categories, product ordering, imagery order, and where personalization appears.'],
 signin:['One connected account','Shoppers use the retailer account they already know. Add a photo and fit details once to enable personal views across the store.','Choose sign-in placement and profile fields while keeping your own customer relationship.'],
 builder:['Outfit builder','Combine pieces, swap garments, choose sizes, and save a complete look.','Choose eligible categories, styling rules, suggested combinations, and where the builder appears.'],
 stylist:['Your brand’s AI stylist','A shopping advisor helps customers discover pieces and complete looks.','Curate its knowledge, tone, recommendations, and persona—from a personal advisor to your creative studio’s point of view.'],
 why:['Personalized sizing','SPREEAI sizing recommends a size using profile and garment information. Coming soon, fit visualizations will help shoppers explore a looser or closer look. Recommendations in this demo are illustrative.','Choose placement, size charts, fit preferences, and how recommendations are explained.'],
 compare:['Side-by-side comparison','See two garments on the same person without leaving the store.','Choose comparison entry points, garment categories, and available views.'],
 colors:['Color comparison','Explore colorways side by side on the same person.','Choose eligible colorways and where color comparisons appear.'],
 twins:['Twins','Preset people let shoppers explore instantly without uploading a photo.','Curate your preset selection and offer it alongside account-linked personalization.'],
 profile:['Account linking','A photo and fit details become part of the retailer’s existing customer account.','Choose profile placement and supported inputs. This local prototype simulates the connection.'],
 saved:['Saved looks','Return to complete outfits and add their pieces to the bag.','Choose how saved looks connect to wishlists, customer accounts, and recommendations.'],
 unlock:['Virtual try-on','Personal views live inside the product gallery and recommendations, ready after one setup.','Choose where views appear, which categories participate, and whether product or personal imagery leads.'],
 poses:['Multi-pose & Flip','Your brand directs the poses, just as it directs a model shoot. Start front-facing, then discover two editorial poses chosen for that garment. Finish with a clearly labeled simulated back view.','Direct poses by garment: a relaxed lean for leather, skirt handling for a wedding dress, or mid-stride leisurewear. Choose the framing, setting, and gallery order.'],
 motion:['Motion','See a playable multi-pose storyboard alongside product photography. This is a simulation, not continuous generated video.','Direct the action by garment: gently turn with a wedding dress, walk or run in leisurewear, or reveal an accessory in close-up. Partners set the movement, environment, framing, and playback.'],
 zoom:['Image detail','Enlarge photography and personal views to inspect details.','Choose magnification and the gallery’s interaction style. Preview resolution limits detail in this demo.'],
};
const steps:Record<string,string[]>={
 collection:['Browse or filter the collection. Desktop hover reveals the model; on mobile, open the product for its model views.','Open a garment. Product and model photography leads into personal views further down.','Set up once through My Account, or choose a Twin. Then continue shopping normally.'],
 recommendations:['Scroll to the curated edit at the bottom of the page.','With Always On enabled, the recommended garments already show your selected person. No extra generation button.','Open a recommendation to inspect the piece, or add two pieces to your comparison edit.'],
 builder:['Build an outfit directly on any product page, starting with the garment you are viewing.','Use each garment menu to swap tops, layers, bottoms, shoes, or accessories. Select the pieces you want.','Save your named look, or choose a size for each selected piece and add the outfit to the demo bag.'],
 stylist:['Meet your digital stylist and play the welcome video with sound.','Choose an occasion or tell the stylist what you are shopping for.','Explore the suggested pieces, swap items in the outfit builder, and save the look you love.'],
 why:['Your suggested size appears beside size selection when a profile or Twin is active.','Watch the coming-soon visualization: the same garment becomes looser or closer-fitting on the same person.','Choose your preferred size on the product page. Edit your profile if your measurements or preferences change.'],
 compare:['Add two pieces to Your edit, or choose Compare this piece on a product.','Both garments appear on the same selected person.','Replace either garment from its menu, then open your preferred piece to explore further.'],
 colors:['Open color comparison on the merino polo.','See both prepared colorways on the same selected person.','Return to the product to continue exploring. Retailers choose which colorways support this feature.'],
 twins:['Choose one of the six preset people. Their measurements describe the twin, not your own body.','Continue with the twin to unlock the personal gallery, recommendations, and comparison.','Change the twin from the collection profile strip whenever you want.'],
 profile:['Use the sample profile, or add a photo and your profile details.','Confirm your visualization choice once. This prototype uses prepared Alex sample results, not live photo inference.','Browse freely: your views and fit context follow you. Return to My Account to edit or remove the local profile.'],
 signin:['Continue as Alex or create a local demo profile. No password or real account is created.','Add the short fit and visualization profile within the same account flow.','Continue shopping with automatic personalization, or explore without an account using a Twin.'],
 saved:['Save a named outfit from the outfit builder.','Open Saved looks from navigation or My Account.','Revisit and edit the outfit, or delete a saved look. Demo looks stay on this device.'],
 unlock:['Sign in to see the sample shopper, or continue instantly with a Twin.','Open any product: personal views appear after product and model photography.','Recommendations and comparisons use the same selected person, without restarting try-on.'],
 poses:['Scroll past the product and model photography to your personal views.','See yourself styled like the brand’s models: folded arms in a leather jacket, a hand on the hip in a polo, or a seated pose to show a trouser’s drape. The brand chooses the direction for each garment.','Select any view to enlarge it. Back views are always simulated illustrations, not verified reconstructions of unseen garment details. This demo uses prepared sample images.'],
 motion:['Scroll to the motion slot after the personal poses.','Watch the preview directly in the gallery. Playback controls and an optional full-screen view are available.','Read the garment-specific creative brief beside the clip. Partners direct the real action; this prepared storyboard illustrates gallery placement only.'],
 zoom:['Select any photograph or personal view to enlarge it.','Use plus and minus to change magnification, and drag to inspect the image.','Reset the view or close it to return to the same product. Detail is limited by the source photograph.'],
};
export default function FeatureNote({panel,inline=false}:{panel:string|null;inline?:boolean}){
 const tutorialsEnabled=useTutorialsEnabled();
 const key=panel||'';
 const [dismissed,setDismissed]=useState(false),[step,setStep]=useState(0);
 const lesson=lessons[key];
 const note=panel?notes[panel]:null;
 if(!note||!tutorialsEnabled)return null;
 const instructions=steps[panel!]||[];
 return <aside className={`feature-note ${inline?'inline-tutorial':''}`}><button className="feature-note-title" onClick={()=>{setDismissed(!dismissed);setStep(0)}} aria-expanded={!dismissed}>✧ {dismissed?'How it works':'Tutorial'} · {note[0]} <span>{dismissed?'+':'−'}</span></button>{!dismissed&&<div>{key==='why'&&<div className="sizing-video-intro"><span>PERSONALIZED SIZE RECOMMENDATION</span><strong>Coming soon · See your preferred fit</strong><p>Watch the same shirt change from regular to relaxed to close-fitting. The person stays the same; the garment’s fit changes.</p></div>}{lesson?<figure className="feature-video"><div className="feature-video-player"><AutoVideo src={lesson.video} poster={lesson.poster} preload="metadata" aria-label={`${note[0]} video demonstration`}>{lesson.captions&&<track kind="captions" src={lesson.captions} srcLang="en" label="English" default/>}</AutoVideo></div><figcaption><span>Yuna · Your Twin guide</span><span>Illustrative demonstration</span></figcaption><button className="text-link feature-video-skip" onClick={()=>setDismissed(true)}>Continue exploring →</button><details><summary>Read the video transcript</summary><p>{lesson.transcript}</p></details></figure>:<p className="feature-video-pending">Twin video walkthrough · In preparation</p>}{key==='poses'&&<div className="pose-creative-examples"><figure><img loading="lazy" src="/always-on-assets/editorial-leather-jacket-alex-1.webp" alt="Alex modeling the leather jacket with his arms folded"/><figcaption>Leather jacket · Arms folded</figcaption></figure><figure><img loading="lazy" src="/always-on-assets/editorial-knit-polo-alex-1.webp" alt="Alex modeling the merino polo with one hand on his hip"/><figcaption>Knit polo · Hand on hip</figcaption></figure><p>One shopper. Different creative direction for every garment. Your brand chooses the stance, gesture, and framing.</p></div>}{key==='why'&&<p className="fit-demo-disclosure"><strong>Coming soon: fit visualization.</strong> Regular, relaxed, and close-fitting looks illustrate different garment ease. These generated previews demonstrate the planned experience; they are not measured size predictions or verified size simulations.</p>}<p>{note[1]}</p><div className="tutorial-step"><span>STEP {step+1} OF {instructions.length}</span><p>{instructions[step]}</p><div>{step>0&&<button className="text-link" onClick={()=>setStep(step-1)}>← Back</button>}<button className="text-link" onClick={()=>step<instructions.length-1?setStep(step+1):setDismissed(true)}>{step<instructions.length-1?'Next →':'Explore this feature →'}</button></div></div><p><strong>For your brand.</strong> {note[2]}</p></div>}</aside>
}
