import {useState} from 'react';
import * as Dialog from '@radix-ui/react-dialog';
import {Ruler} from '@phosphor-icons/react/dist/csr/Ruler';
import {X} from '@phosphor-icons/react/dist/csr/X';
import {useConnectedProfile} from './connection';
import {usePersonalFit} from './personalization';
import useShoppingState from './useShoppingState';
import IdentityPortrait from './IdentityPortrait';
import type {Product} from './data';
import './fit-details.css';
export default function FitDetails({product,selected,onSize}:{product:Product;selected:string;onSize:(size:string)=>void}){
 const [open,setOpen]=useState(false);const {identity}=useConnectedProfile();const fit=usePersonalFit(product);const [unit,setUnit]=useShoppingState('profile-unit',()=>navigator.language==='en-US'?'imperial':'metric');const active=selected||fit.recommended||product.sizes[0];const zones=fit.map?.sizes.find(s=>s.size===active)?.zones||[];
 const heightText=identity?.height?(unit==='metric'?`${Math.round(identity.height)} cm`:`${Math.floor(Math.round(identity.height/2.54)/12)}′ ${Math.round(identity.height/2.54)%12}″`):'Measurements not supplied';
 const verdicts:Record<string,string>={true:'True to size',snug:'Close fit',room:'Room to move',loose:'Relaxed fit',too_small:'May feel tight',short:'Shorter length',long:'Longer length'};
 const format=(n:number)=>`${Number((unit==='metric'?n*2.54:n).toFixed(1))} ${unit==='metric'?'cm':'in'}`;
 return <Dialog.Root open={open} onOpenChange={setOpen}><Dialog.Trigger className="fit-details-trigger"><Ruler size={20}/>Fit details</Dialog.Trigger><Dialog.Portal><Dialog.Overlay className="overlay"/><Dialog.Content className="fit-details-modal" aria-describedby="fit-details-description"><div className="fit-details-head"><Dialog.Title>Your fit details.</Dialog.Title><Dialog.Close aria-label="Close fit details"><X size={24}/></Dialog.Close></div><div className="fit-details-body"><Dialog.Description id="fit-details-description">{product.name}</Dialog.Description>{identity&&<div className="fit-person"><IdentityPortrait identity={identity}/><span>{identity.name} · {heightText}</span></div>}<div className="fit-details-controls"><label>Size<select value={active} onChange={e=>onSize(e.target.value)}>{product.sizes.map(s=><option key={s}>{s}</option>)}</select></label><div className="unit-toggle"><button aria-pressed={unit==='metric'} onClick={()=>setUnit('metric')}>cm</button><button aria-pressed={unit==='imperial'} onClick={()=>setUnit('imperial')}>in</button></div></div>{zones.length?<div className="fit-details-zones">{zones.map(z=><article key={z.point}><h3>{z.point.replace(/_/g,' ')}</h3><p>Garment / chart: <strong>{format(z.size_in)}</strong>{z.body_in!==undefined&&<> · Body: <strong>{format(z.body_in)}</strong></>}</p><small>{z.verdict?verdicts[z.verdict]||'Fit guidance':'Size chart information'}</small></article>)}</div>:<div className="fit-details-empty" role="status"><h3>{fit.status==='loading'?'Checking this garment’s fit data…':'Detailed measurements aren’t available for this selection.'}</h3><p>{identity?'You can still choose a size and view the garment. We will only show measurements supplied for this person and product.':'Add your photo and measurements or choose a Twin for size guidance.'}</p></div>}</div><div className="fit-details-footer"><p className="fine">Sizing guidance is an estimate. Try-on images do not measure your body.</p><button className="primary" onClick={()=>setOpen(false)}>Done</button></div></Dialog.Content></Dialog.Portal></Dialog.Root>
}
