import SizingGuidance from './SizingGuidance';
import TryOnBeta from './TryOnBeta';
import {Link} from 'react-router';
import type {Product} from './data';
import {useConnectedProfile} from './connection';
import {usePersonalFit,useSizePreview,fitWords} from './personalization';
import {isOneSize,sizeLabel} from './fit-scale';
import {sizeFitLabel} from './fit-preview';
import LoadingBar from './LoadingBar';
export function FitSummary({product,size}:{product:Product;size:string}){const {identity}=useConnectedProfile();const fit=usePersonalFit(product);const words=fitWords(fit.map,size||fit.recommended||'');return <div className="automatic-fit-summary" aria-live="polite">{isOneSize(product.sizes)?<p>One size · See product details for dimensions.</p>:!identity?<Link to="/account">My Account · Discover your fit</Link>:fit.recommended?<><strong>{fit.recommendationSource==='simulated'?`Demo model reference size: ${fit.recommended}.`:fit.recommendationSource==='twin'?`${identity.name}’s reference size is ${fit.recommended}.`:`Our recommended size for ${identity.kind==='twin'?identity.name:'you'} is ${fit.recommended}.`}</strong><p>{fit.recommendationSource==='simulated'?'Demo guidance based on your model’s reference size. Select any size below and compare its generated silhouette. This is not calibrated garment-specific sizing.':words.length?words.map(w=>`${w.point}: ${w.label.toLowerCase()}`).join(' · '):fit.recommendationSource==='twin'?'Based on the twin’s saved size; a garment-specific recommendation is not available.':fit.fitNote||'Based on your profile and this garment’s sizing data.'}</p></>:<p>{fit.status==='error'?fit.error:'Finding your recommended size…'}</p>}{!isOneSize(product.sizes)&&<SizingGuidance/>}</div>}
export function FitOptions({product,size,onSize}:{product:Product;size:string;onSize:(s:string)=>void}){const fit=usePersonalFit(product);return <div className="fit-options"><div className="shopping-sizes" role="group" aria-label="Garment sizes">{product.sizes.map(s=>{const step=fit.recommended?sizeFitLabel(product.sizes,s,fit.recommended,fit.map):'';return <button key={s} aria-pressed={size===s} onClick={()=>onSize(s)}><span>{sizeLabel(s)}</span>{step&&<small>{s===fit.recommended&&fit.recommendationSource==='twin'?'Starting size':step}</small>}</button>})}</div>{fit.recommended&&<p className="fit-step-note">Choose a size to see its silhouette. Fit labels use garment guidance where available, otherwise the size steps from your starting size.</p>}</div>}
export default function FitSelector({product,size,onSize}:{product:Product;size:string;onSize:(size:string)=>void}){const {identity}=useConnectedProfile();const fit=usePersonalFit(product);const selected=size||fit.recommended||'';const image=useSizePreview(product,selected);const words=fitWords(fit.map,selected);return <div className="fit-shopping"><div className="fit-shopping-image">{image.url?<img src={image.url} alt={`${product.name} on ${identity?.name}${image.selected?`, size ${image.selected}`:""}`}/>:<img className={identity&&!image.reason?'awaiting-view':''} src={product.model} alt={`${product.name} — original model photography`}/>}<div className="fit-preview-caption">{image.status==='loading'?<LoadingBar label="Preparing your selected size"/>:image.status==='error'?<p>Size preview temporarily unavailable.</p>:image.url?<><small>ON {identity?.name.toUpperCase()}</small>{image.selected&&<strong>Size {sizeLabel(image.selected)}</strong>}{image.fitNote&&<p>{image.fitNote}</p>}</>:<p>{image.reason||'Original collection photography'}</p>}</div></div><div className="fit-shopping-copy">{image.url&&<TryOnBeta/>}<p className="eyebrow">{product.name}</p><h2>Your size.<br/>Your kind of fit.</h2><FitSummary product={product} size={selected}/><FitOptions product={product} size={selected} onSize={onSize}/><div className="fit-language">{words.map(w=><div key={w.point}><span>{w.point}</span><strong>{w.label}</strong></div>)}</div><p className="fine">{identity?.kind==='twin'?'Fit guidance describes your chosen twin. Use your own photo and measurements for personal sizing.':'Generated views illustrate a size; they do not replace physical fit assessment.'}</p></div></div>}
