import {useRef} from 'react';
import AutoVideo from './AutoVideo';
import media from './media.json';
const chapters=[
 {label:'Welcome',title:'Welcome to SPREEAI.',body:'Meet Always On: no extra try-on buttons, no disruption to the way your customers already shop. SPREEAI fits naturally into your existing online or in-store journey, adding personalization inside the experience your brand has already built. Your brand. Your flow. Enhanced.',detail:'This is a demo of what your storefront could become. Meet Yuna and Malik, then follow the journey from one account setup to personalization that stays with your shopper.',items:['No extra try-on steps','Native to your online or in-store journey','Your existing shopping flow, enhanced']},
 {label:'Your account',title:'Your journey begins with your account.',body:'Sign in to the store as you normally would, or create an account if you’re new. SPREEAI connects with the retailer’s existing account system, so shoppers don’t need a separate SPREEAI login.',detail:'For partners, the customer relationship stays in your account experience. For shoppers, one familiar sign-in opens a more personal way to browse.',items:['Sign in or create a store account','One connected customer profile','Explore with a Twin if you’re not ready to sign in']},
 {label:'Your profile',title:'A photo. A few details. Saved once.',body:'Inside your account, add a clear photo, your height and weight, and the fit details your retailer needs. Choose your fit preferences and confirm that you want to enable your personal visualization profile.',detail:'Your saved profile powers the experience across the site. Edit or remove it from My Account whenever you want. This local demo uses prepared sample results; uploaded photos stay in the current tab.',items:['Your photo','Height, weight, and fit preferences','Your choice to enable personalization']},
 {label:'Always On',title:'Now, it’s simply part of shopping.',body:'Browse the garments, hover to see a model, and open a product. As you scroll through the gallery, your own views are already there—alongside sizing, multiple poses, and motion previews. Recommendations at the bottom already show the pieces on you.',detail:'No repeated uploads. No separate try-on session for every piece. Your profile remains connected until you choose to change it or switch it off.',items:['Personal views in the product gallery','Fit guidance beside size selection','Recommendations, outfits, and comparison in context']},
 {label:'Make it yours',title:'Your storefront. Your feature set.',body:'Choose the experience that works for your business: virtual try-on, sizing, outfit builder, side-by-side comparison, Twins, or a stylist curated by your creative team. Customize placement, imagery order, tone, and styling. Always begin front-facing, then show two poses chosen by the brand, such as folded arms or a hand on the hip. Finish with a simulated back view, since unseen details cannot be reliably predicted. Partners also direct video actions for each garment.',detail:'Explore freely after this walkthrough. “How it works” tutorials stay beside features throughout the store, and feature panels explain what shoppers can do and what partners can customize.',items:['Brand-curated AI stylist','Select and tailor each feature','Clearly labeled concept previews']},
];
export default function Guide({step,setStep,onAccount,onTwin,onClose}:{step:number;setStep:(n:number)=>void;onAccount:()=>void;onTwin:()=>void;onClose:()=>void}){
 const content=useRef<HTMLDivElement>(null);
 const changeStep=(next:number)=>{setStep(next);content.current?.scrollTo({top:0,behavior:'instant'})};
 const chapter=chapters[step];const clip=media.guideChapters[step];
 return <><div className="guide-content" ref={content}><div className="guide-art"><div className="guide-brand"><img src="/sa-logo.svg" alt="SPREEAI SA monogram"/><span>SPREEAI · PARTNER DEMO</span></div><div className="guide-moving-image">{clip?.video?<AutoVideo soundClass="guide-sound" key={step} src={clip.video} poster={clip.poster} aria-label={`Yuna and Malik explain ${chapter.label}`}><track key={step} kind="captions" src={clip.captions} srcLang="en" label="English" onLoad={e=>{const cues=e.currentTarget.track.cues;if(cues)for(const cue of Array.from(cues)){const c=cue as VTTCue;c.snapToLines=false;c.line=62;c.size=88;}}} default/></AutoVideo>:<img src="/always-on-assets/editorial.webp" alt="The Always On collection"/>}<div className="guide-headline"><span>A MORE PERSONAL WAY TO SHOP</span><h2>Always<br/> On.</h2></div></div></div><div className="guide-copy"><p className="eyebrow">YUNA & MALIK / YOUR DIGITAL HOSTS</p><div className="guide-chapters" aria-label="Walkthrough chapters">{chapters.map((c,i)=><button key={c.label} onClick={()=>changeStep(i)} aria-current={i===step?'step':undefined}><span>{String(i+1).padStart(2,'0')}</span><small>{c.label}</small></button>)}</div><p className="chapter-count">STEP {step+1} OF 5</p><h2>{chapter.title}</h2><p>{chapter.body}</p><ul className="guide-points">{chapter.items.map(item=><li key={item}>{item}</li>)}</ul><p className="guide-detail">{chapter.detail}</p><p className="fine">Interactive demonstration · No real orders or payments · Generated sample views</p></div></div><div className="guide-actions"><button className="primary full" onClick={()=>step<4?changeStep(step+1):onAccount()}>{step<4?`Continue: ${chapters[step+1].label}`:'Begin with your store account'} <span>→</span></button><div className="guide-secondary">{step>0&&<button className="text-link" onClick={()=>changeStep(step-1)}>← Back</button>}<button className="text-link" onClick={step===4?onTwin:onClose}>{step===4?'Explore with a Twin':'Explore on my own'}</button></div></div></>
}
