import TryOnBeta from './TryOnBeta';
import {useLayoutEffect,useRef,useState} from 'react';
import {MagnifyingGlassPlus} from '@phosphor-icons/react/dist/csr/MagnifyingGlassPlus';
import * as Dialog from '@radix-ui/react-dialog';
import './image-zoom.css';
export default function ImageZoom({src,alt,onError,allowOriginal=false,expandedTryOn=false}:{src?:string;alt:string;onError?:()=>void;allowOriginal?:boolean;expandedTryOn?:boolean}){
 const tryOn=allowOriginal||expandedTryOn;
 const [sourceWidth,setSourceWidth]=useState(0);
 useLayoutEffect(()=>{if(!tryOn||!src)return;const widths=Array.from(document.images).filter(img=>!img.closest('.image-zoom')&&(img.src===src||img.currentSrc===src||img.getAttribute('src')===src)).map(img=>{const box=img.getBoundingClientRect();return getComputedStyle(img).objectFit==='contain'&&img.naturalWidth?Math.min(box.width,box.height*img.naturalWidth/img.naturalHeight):box.width});setSourceWidth(Math.max(0,...widths))},[src,tryOn]);
 const [zoom,setZoom]=useState(1),[natural,setNatural]=useState({width:0,height:0}),[space,setSpace]=useState({width:0,height:0});
 const viewport=useRef<HTMLDivElement>(null),drag=useRef<{x:number;y:number;left:number;top:number}|null>(null);
 useLayoutEffect(()=>{const e=viewport.current;if(!e)return;const update=()=>setSpace({width:e.clientWidth,height:e.clientHeight});update();const observer=new ResizeObserver(update);observer.observe(e);return()=>observer.disconnect()},[]);
 const border=tryOn?8:space.width<500?16:24;
 const fit=natural.width?Math.min((space.width-border*4)/natural.width,(space.height-border*4)/natural.height,1):0;
 // An enlarged try-on must not be reduced below its source card simply to fit height.
 const available=Math.max(1,space.width-border*4);
 const baseWidth=tryOn?(window.matchMedia('(max-width:720px)').matches?available:Math.max(natural.width*fit,Math.min(available,Math.max(sourceWidth*1.12,Math.min(760,space.width*.48))))):natural.width*fit;
 const width=Math.max(1,baseWidth*zoom),height=Math.max(1,natural.width?baseWidth*natural.height/natural.width*zoom:1);
 useLayoutEffect(()=>{const e=viewport.current;if(e){e.scrollLeft=(e.scrollWidth-e.clientWidth)/2;e.scrollTop=zoom===1?0:(e.scrollHeight-e.clientHeight)/2}},[zoom,src,space.width,space.height,natural.width]);
 return <div className={"image-zoom"+(tryOn?" image-zoom-tryon":"")} data-zoom={zoom}><div className="image-zoom-controls" role="group" aria-label="Image magnification"><button className="image-zoom-in" type="button" aria-label="Increase magnification" disabled={zoom===2} onClick={()=>setZoom(level=>Math.min(2,level+1))}><MagnifyingGlassPlus size={20} aria-hidden="true"/></button><span className="image-zoom-label">Zoom</span>{[1,2].map(level=><button key={level} type="button" aria-label={`Zoom ${level}x`} aria-pressed={zoom===level} onClick={()=>setZoom(level)}>{level}×</button>)}{allowOriginal&&src&&<Dialog.Root><Dialog.Trigger className="image-zoom-original" aria-label={`Expand full image: ${alt}`}>Full image</Dialog.Trigger><Dialog.Portal><Dialog.Overlay className="image-fullscreen-overlay"/><Dialog.Content className="image-fullscreen"><header><Dialog.Title>{alt}</Dialog.Title><Dialog.Description className="sr-only">Full-screen try-on image. Zoom to inspect details, then close to return to your preview.</Dialog.Description><Dialog.Close aria-label="Close full image">×</Dialog.Close></header><ImageZoom expandedTryOn src={src} alt={alt} onError={onError}/><TryOnBeta/></Dialog.Content></Dialog.Portal></Dialog.Root>}<span className="image-zoom-hint" aria-live="polite">{zoom>1?'Drag or scroll to explore':tryOn?'Scroll to explore':'Full image'}</span></div><div ref={viewport} className="image-zoom-viewport" tabIndex={0} role="region" aria-label={`${alt}. ${zoom} times zoom. Use arrow keys or scroll to explore.`} onPointerDown={e=>{if((zoom===1&&!tryOn)||e.pointerType!=='mouse'||e.button!==0)return;const el=e.currentTarget;drag.current={x:e.clientX,y:e.clientY,left:el.scrollLeft,top:el.scrollTop};el.setPointerCapture(e.pointerId)}} onPointerMove={e=>{const d=drag.current;if(d){e.currentTarget.scrollLeft=d.left-e.clientX+d.x;e.currentTarget.scrollTop=d.top-e.clientY+d.y}}} onPointerUp={()=>{drag.current=null}} onPointerCancel={()=>{drag.current=null}}><div className="image-zoom-canvas" style={{width:width+border*4,height:height+border*4}}><img src={src} alt={alt} draggable={false} onLoad={e=>setNatural({width:e.currentTarget.naturalWidth,height:e.currentTarget.naturalHeight})} onError={onError} style={{width:width+border*2,height:height+border*2,borderWidth:border,visibility:natural.width?'visible':'hidden'}}/></div></div></div>
}
