import {useEffect,useState} from 'react';
import {Link} from 'react-router';
import {products,editorialImage} from './data';
import {configure,readJourney,subscribe,togglePiece,changeJourney,updatePiece,occasions,resetJourney} from '../../../journey/store.js';
import './journey.css';
configure(products);
export function useJourney(){const [journey,setJourney]=useState(readJourney);useEffect(()=>subscribe(()=>setJourney(readJourney())),[]);return journey}
export function SavePiece({id,isSample,onStart}:{id:string;isSample:boolean;onStart:()=>void}){
 const j=useJourney(),saved=j.items.some(x=>x.id===id);
 return <button className="text-link journey-save" aria-pressed={saved} disabled={!saved&&j.items.length>=12} onClick={()=>isSample?togglePiece(id):onStart()}>{saved?'✓ Saved to your edit':j.items.length>=12?'Edit full · 12 pieces':'+ Save to your edit'}</button>
}
export default function Journey({isSample,onStart,onClose}:{isSample:boolean;onStart:()=>void;onClose:()=>void}){
 const j=useJourney();const [notice,setNotice]=useState('');
 return <div className="modal-body connected-edit"><p className="eyebrow">ONLINE · WITH YOUR ASSOCIATE · IN STORE</p><h2>Your edit, wherever<br/>you take it.</h2><p>Save the pieces you love. Refine the selection with your associate, then pick up where you left off in store.</p>
 {!isSample?<div className="journey-start"><h3>Explore as Alex</h3><p>This connected journey uses Alex’s prepared sample profile. Your uploaded photo and personal details are not shared with the associate demo.</p><button className="primary" onClick={onStart}>Use Alex’s sample journey →</button></div>:<>
 <div className="journey-profile"><img src="/always-on-assets/person-1-0.webp" alt="Alex, sample client"/><div><strong>Alex’s personal edit</strong><span>Sample profile · Same browser only</span></div><span>{j.items.length} / 12 pieces</span></div>
 <label className="journey-occasion">What are you dressing for?<select value={j.occasion} onChange={e=>changeJourney(x=>{x.occasion=e.target.value;x.requested=false})}>{occasions.map(x=><option key={x}>{x}</option>)}</select></label>
 <p className="fine">Your brief helps the associate curate; it does not automatically generate outfit recommendations.</p>
 {j.items.length?<div className="journey-items">{j.items.map(item=>{const p=products.find(x=>x.id===item.id)!;return <article key={item.id}><Link to={`/product/${p.id}`} onClick={onClose}><img src={editorialImage(p,1,true)} alt={`${p.name} on Alex · sample`}/></Link><div><Link to={`/product/${p.id}`} onClick={onClose}><h3>{p.name}</h3></Link><p>{p.category}</p><label>Preferred size<select value={item.size} onChange={e=>updatePiece(p.id,{size:e.target.value})}><option value="">Confirm with associate</option>{p.sizes.map(x=><option key={x}>{x}</option>)}</select></label><label>Next step<select value={item.response} onChange={e=>updatePiece(p.id,{response:e.target.value as typeof item.response})}><option value="">Keep in my edit</option><option value="interested">Interested</option><option value="fitting">Try in store</option><option value="question">Ask my associate</option></select></label>{item.outcome&&<p className="journey-outcome">After the fitting: {item.outcome==='keep'?'Saved for later':item.outcome==='pass'?'Not for me':'Purchased · sample outcome'}</p>}<button className="text-link" onClick={()=>togglePiece(p.id)}>Remove</button></div></article>})}</div>:<div className="journey-empty"><h3>A considered edit starts with one piece.</h3><p>Browse the collection and revisit your personal views in My Account → History.</p><button className="secondary" onClick={onClose}>Explore the collection</button></div>}
 {j.items.length>0&&<section className="journey-next"><h3>Bring your edit to your associate.</h3><p>Camille can review your preferences and confirm availability before a fitting.</p><label className="checkbox"><input type="checkbox" checked={j.consent} onChange={e=>changeJourney(x=>{x.consent=e.target.checked;x.requested=false})}/><span>Include my sample edit in the associate appointment preview.</span></label><button className="primary" disabled={!j.consent} onClick={()=>{changeJourney(x=>{x.requested=true});setNotice('Appointment request prepared in this browser. Nothing was sent or booked.')}}>{j.requested?'✓ Request prepared · demo':'Prepare appointment request'}</button><p className="fine">No message, booking or stock reservation. Real availability and supported sizing need confirmation.</p>{notice&&<p role="status">{notice}</p>}{j.requested&&<p className="journey-outcome">Your sample preferences are ready for the associate to review.</p>}</section>}
 <details className="journey-demo"><summary>Continue the demo as an associate</summary><p>Switch roles to review Alex’s sample selection. This public preview has no real customer accounts.</p><a className="text-link" href={`${import.meta.env.BASE_URL}associate/in-store/?journey=alex`}>Open the in-store workspace</a><a className="text-link" href={`${import.meta.env.BASE_URL}associate/vic/?journey=alex`}>Open VIC clienteling</a><button className="text-link" onClick={()=>{resetJourney();setNotice('Alex’s shared sample edit was cleared.')}}>Clear shared sample edit</button></details>
 </>}
 <details className="journey-film"><summary>Watch Yuna explain the connected journey</summary><video controls playsInline preload="none" poster={`${import.meta.env.BASE_URL}associate/assets/vic.jpg`}><source src={`${import.meta.env.BASE_URL}journey/connected-guide.mp4`} type="video/mp4"/><track kind="captions" src={`${import.meta.env.BASE_URL}journey/connected-guide.vtt`} srcLang="en" label="English" default/></video></details>
 </div>
}
