import {imageFilename} from './image-filename';
import TryOnBeta from './TryOnBeta';
import ImageZoom from './ImageZoom';
import {useState,type ReactNode} from 'react';
import * as Dialog from '@radix-ui/react-dialog';
import {Link} from 'react-router';
import {FacebookLogo} from '@phosphor-icons/react/dist/csr/FacebookLogo';
import {XLogo} from '@phosphor-icons/react/dist/csr/XLogo';
import {ThreadsLogo} from '@phosphor-icons/react/dist/csr/ThreadsLogo';
import {InstagramLogo} from '@phosphor-icons/react/dist/csr/InstagramLogo';
import {TiktokLogo} from '@phosphor-icons/react/dist/csr/TiktokLogo';
import {SnapchatLogo} from '@phosphor-icons/react/dist/csr/SnapchatLogo';
import {ChatCircleDots} from '@phosphor-icons/react/dist/csr/ChatCircleDots';
import {LinkSimple} from '@phosphor-icons/react/dist/csr/LinkSimple';
type Piece={id:string;name:string};
export default function LookPreview({images,title,pieces,children,detail,onProduct,isTryOn=false,exportPerson,exportSize,imagePieces}:{images:string[];title:string;pieces:Piece[];children:ReactNode;detail?:string;onProduct?:()=>void;isTryOn?:boolean;exportPerson?:string;exportSize?:string;imagePieces?:Piece[]}){
 const [open,setOpen]=useState(false),[index,setIndex]=useState(0),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[failed,setFailed]=useState(false);
 const url=images[index]||images[0],productLink=pieces[0]?new URL(`/spreeai-always-on-demo/online/product/${pieces[0].id}/`,window.location.origin).href:window.location.href;
 async function imageFile(){const response=await fetch(url,{credentials:'omit'});if(!response.ok)throw Error('Image unavailable');const blob=await response.blob();const bitmap=await createImageBitmap(blob);const canvas=document.createElement('canvas');canvas.width=bitmap.width;canvas.height=bitmap.height;canvas.getContext('2d')!.drawImage(bitmap,0,0);bitmap.close();const png=await new Promise<Blob>((resolve,reject)=>canvas.toBlob(value=>value?resolve(value):reject(Error('Export unavailable')),'image/png'));return new File([png],imageFilename({garments:(imagePieces?.[index]?[imagePieces[index]]:pieces).map(p=>p.name),title,person:exportPerson,size:exportSize,view:images.length>1?index+1:undefined}),{type:'image/png'})}
 async function download(){setBusy(true);setMessage('');try{const file=await imageFile(),objectUrl=URL.createObjectURL(file),link=document.createElement('a');link.href=objectUrl;link.download=file.name;link.click();setTimeout(()=>URL.revokeObjectURL(objectUrl),60000);setMessage('Your image is ready in Downloads.')}catch{setMessage(isTryOn?'Select Full image to expand your preview.':'Open the original image below to save it from your browser.')}finally{setBusy(false)}}
 async function share(){setBusy(true);setMessage('');try{if(!navigator.share){setMessage('Use a social link below, or copy the product link. Save the image to include it in your post.');return}const file=await imageFile();if(navigator.canShare?.({files:[file]}))await navigator.share({title:'My SPREEAI look',text:title,files:[file]});else await navigator.share({title,text:title,url:productLink})}catch(e){if(!(e instanceof DOMException&&e.name==='AbortError'))setMessage('Sharing is unavailable here. Save the image or use a product-sharing link below.')}finally{setBusy(false)}}
 async function shareTikTok(){setMessage('');try{if(navigator.share){await navigator.share({title,text:'My Always On find: '+title,url:productLink});return}await navigator.clipboard.writeText(productLink);setMessage('Product link copied. Paste it in TikTok, or save your image to create a photo post.')}catch(e){if(!(e instanceof DOMException&&e.name==='AbortError'))setMessage('Save your image and add it to TikTok, or copy the product link.')}}
 return <Dialog.Root open={open} onOpenChange={value=>{setOpen(value);setMessage('');setFailed(false)}}><Dialog.Trigger asChild><button className="look-preview-trigger" aria-label={`Enlarge ${title}`}>{children}<span className="look-expand" aria-hidden="true">View look</span></button></Dialog.Trigger><Dialog.Portal><Dialog.Overlay className="overlay look-lightbox-overlay"/><Dialog.Content className="look-lightbox" aria-describedby="look-viewer-description"><Dialog.Close className="look-close" aria-label="Close enlarged look">×</Dialog.Close><div className="look-lightbox-image">{!failed?<ImageZoom allowOriginal={isTryOn} key={url} src={url} alt={title} onError={()=>setFailed(true)}/>:<p>This preview link is unavailable. Open the product below to view your look again.</p>}{images.length>1&&<div className="look-image-controls">{images.map((_,i)=><button key={i} aria-pressed={index===i} onClick={()=>{setIndex(i);setFailed(false);setMessage('')}}>View {i+1}</button>)}</div>}</div><div className="look-lightbox-details"><p className="eyebrow">YOUR ALWAYS ON GALLERY</p><Dialog.Title>{title}</Dialog.Title><Dialog.Description id="look-viewer-description">{detail||'Your look, up close. Revisit the pieces or keep the image.'}</Dialog.Description>{isTryOn&&<TryOnBeta/>}<div className="look-download-actions"><button className="primary" disabled={busy||failed||!url} onClick={()=>void download()}>Save image</button><button className="secondary" disabled={busy||failed||!url} onClick={()=>void share()}>Share look</button></div>{message&&<p role="status" className="look-share-status">{message}</p>}<div className="look-products"><h3>The pieces</h3>{pieces.map(p=><Link key={p.id} to={`/product/${p.id}`} onClick={()=>{setOpen(false);onProduct?.()}}>{p.name}<span>View product</span></Link>)}</div><div className="look-social"><p>Share the product</p><div className="look-social-icons">{[
 {name:'Facebook',Icon:FacebookLogo,href:`https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(productLink)}`},
 {name:'X',Icon:XLogo,href:`https://twitter.com/intent/tweet?url=${encodeURIComponent(productLink)}&text=${encodeURIComponent('My Always On find: '+title)}`},
 {name:'Threads',Icon:ThreadsLogo,href:`https://www.threads.com/intent/post?text=${encodeURIComponent('My Always On find: '+title+' '+productLink)}`}
 ].map(({name,Icon,href})=><a key={name} href={href} target="_blank" rel="noreferrer" aria-label={`Share on ${name}`} title={name}><Icon size={22} aria-hidden="true"/></a>)}<button aria-label="Share to Instagram" title="Instagram" disabled={busy||failed||!url} onClick={()=>{if(typeof navigator.share==='function')void share();else setMessage('To share on Instagram, select Save image, then add the downloaded photo to a post or story in Instagram.')}}><InstagramLogo size={22} aria-hidden="true"/></button><button onClick={()=>void shareTikTok()} aria-label="Share to TikTok" title="Choose TikTok in your device share menu, or copy the link"><TiktokLogo size={22} aria-hidden="true"/></button><a href={`https://www.snapchat.com/share?link=${encodeURIComponent(productLink)}`} target="_blank" rel="noreferrer" aria-label="Share on Snapchat" title="Snapchat"><SnapchatLogo size={22} aria-hidden="true"/></a><a href={`sms:?body=${encodeURIComponent('My Always On find: '+title+' '+productLink)}`} aria-label="Share by SMS" title="SMS"><ChatCircleDots size={22} aria-hidden="true"/></a><button aria-label="Copy product link" title="Copy link" onClick={()=>void navigator.clipboard.writeText(productLink).then(()=>setMessage('Product link copied.')).catch(()=>setMessage('Copy the product address after opening its page.'))}><LinkSimple size={22} aria-hidden="true"/></button></div></div>{url&&!isTryOn&&<a className="look-original text-link" href={url} target="_blank" rel="noreferrer">Open original image</a>}<p className="fine">Save the image to post on Instagram or another app. Product links open the garment page.</p></div></Dialog.Content></Dialog.Portal></Dialog.Root>
}
