import {useState} from 'react';
import {EnvelopeSimple} from '@phosphor-icons/react/dist/csr/EnvelopeSimple';
import {InstagramLogo} from '@phosphor-icons/react/dist/csr/InstagramLogo';
import {PinterestLogo} from '@phosphor-icons/react/dist/csr/PinterestLogo';
import {ShoppingBag} from '@phosphor-icons/react/dist/csr/ShoppingBag';
import {ArrowRight} from '@phosphor-icons/react/dist/csr/ArrowRight';
import type {Brief} from './stylist-conversation';
export default function StylistProfile({brief,onChange}:{brief:Brief;onChange:(next:Brief)=>void}){
 const [open,setOpen]=useState(false),[notes,setNotes]=useState(brief.wardrobe),[consent,setConsent]=useState(false);
 return <section className="stylist-profile"><div className="stylist-profile-top"><div><small>YOUR STYLE, YOUR TERMS</small><h3>A little more you.</h3><p>Choose a direction. Change it whenever you like.</p></div><button className="stylist-profile-toggle" onClick={()=>setOpen(!open)} aria-expanded={open}>Your wardrobe & inspiration <ArrowRight size={17}/></button></div><div className="stylist-directions" aria-label="Style direction">{(['Feminine','Masculine','A mix'] as const).map(value=><button key={value} aria-pressed={brief.presentation===value} onClick={()=>onChange({...brief,presentation:value})}>{value}<small>{value==='Feminine'?'Shape, texture & expression':value==='Masculine'?'Tailoring, layers & ease':'Explore without boundaries'}</small></button>)}</div>{open&&<div className="stylist-connections"><div><h4>Start with what you already love.</h4><p>Add pieces you own, favorite colors, or details from a saved look. Your stylist will use these words to refine this conversation.</p><label htmlFor="wardrobe-notes">Your wardrobe & style notes</label><textarea id="wardrobe-notes" maxLength={1200} rows={4} value={notes} onChange={e=>{setNotes(e.target.value);setConsent(false)}} placeholder="I own navy tailored trousers and white sneakers. I like relaxed linen, no heels. I need a jacket for work."/><label className="stylist-consent"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/>Use these details for this conversation.</label><div className="stylist-profile-actions"><button disabled={!consent||!notes.trim()} onClick={()=>onChange({...brief,wardrobe:notes.trim()})}>Use my style notes</button><button onClick={()=>{setNotes('');setConsent(false);onChange({...brief,wardrobe:''})}}>Clear notes</button></div><p className="stylist-private-note">Kept in this open stylist session. Closing the stylist clears these notes. No account is connected and no email or social content is imported.</p></div><div className="stylist-source-list"><h4>Bring your world into your wardrobe.</h4>{[{name:'Purchase history',Icon:ShoppingBag,detail:'Retailer account connection is not available in this demo. Add pieces you own in your notes.'},{name:'Gmail receipts',Icon:EnvelopeSimple,detail:'Receipt import needs an approved Google connection. You can describe a purchase in your notes.'},{name:'Instagram',Icon:InstagramLogo,detail:'Personal Instagram accounts cannot connect through the supported API. Describe the details you love from a look.'},{name:'Pinterest',Icon:PinterestLogo,detail:'Board import needs an approved Pinterest connection. Share the colors, shapes, and fabrics you saved in your notes.'}].map(({name,Icon,detail})=><details key={name}><summary><Icon size={21}/><span>{name}<small>Not connected</small></span><span aria-hidden="true">+</span></summary><p>{detail}</p></details>)}</div></div>}</section>
}
