import WardrobePanel from './WardrobePanel';
import {wardrobeContext,type WardrobeEntry} from './stylist-wardrobe';
import useShoppingState from './useShoppingState';
import * as Dialog from '@radix-ui/react-dialog';
import {Link} from 'react-router';
import {Microphone} from '@phosphor-icons/react/dist/csr/Microphone';
import {SpeakerHigh} from '@phosphor-icons/react/dist/csr/SpeakerHigh';
import {SpeakerSlash} from '@phosphor-icons/react/dist/csr/SpeakerSlash';
import {Stop} from '@phosphor-icons/react/dist/csr/Stop';
import {Waveform} from '@phosphor-icons/react/dist/csr/Waveform';
import {PaperPlaneTilt} from '@phosphor-icons/react/dist/csr/PaperPlaneTilt';
import {products} from './data';import type {Product} from './data';
import {emptyBrief,understand,selectPieces,completePieces,reasonFor} from './stylist-conversation';
import {useStylistVoice} from './useStylistVoice';
import type {Brief} from './stylist-conversation';

import CompareLooks from './CompareLooks';import CompleteLook from './CompleteLook';
import './voice-stylist.css';
import './stylist-workspace.css';
import {stylistSpeech,type StylistSpeechKey} from './stylist-speech';
const greeting=stylistSpeech.greeting;
const personalities=[{id:'studio',name:'Creative studio',detail:'Considered. Confident. Refined.'},{id:'advisor',name:'Personal advisor',detail:'Warm. Curious. Approachable.'},{id:'editorial',name:'Editorial voice',detail:'Expressive. Fashion forward.'}];
export default function VoiceStylist({onBag,onProduct}:{onBag:(items:{id:string;size:string}[])=>void;onProduct?:()=>void}){
 const [brief,setBrief]=useShoppingState('stylist-1',{...emptyBrief}),[tone,setTone]=useShoppingState('stylist-2','studio'),[started,setStarted]=useShoppingState('stylist-3',false),[text,setText]=useShoppingState('stylist-4',''),[transcript,setTranscript]=useShoppingState<{who:string;text:string}[]>('stylist-transcript',[{who:'stylist',text:greeting}]),[choices,setChoices]=useShoppingState('stylist-5',['Feminine','Masculine','A mix']),[pieces,setPieces]=useShoppingState<Product[]>('stylist-6',[]),[offset,setOffset]=useShoppingState('stylist-7',0),[mode,setMode]=useShoppingState<'discover'|'compare'|'outfit'>('stylist-8','discover'),[anchor,setAnchor]=useShoppingState<Product|null>('stylist-9',null);
 const [panel,setPanel]=useShoppingState<'wardrobe'|'history'|'voice'|null>('stylist-11',null),[cardPage,setCardPage]=useShoppingState('stylist-12',0),[historyPage,setHistoryPage]=useShoppingState('stylist-13',0),[notes,setNotes]=useShoppingState('stylist-14',''),[wardrobeEntries,setWardrobeEntries]=useShoppingState<WardrobeEntry[]>('stylist-15',[]);
 const [mobileView,setMobileView]=useShoppingState<'talk'|'edit'>('stylist-16','talk');
 const [lastSpeech,setLastSpeech]=useShoppingState<StylistSpeechKey>('stylist-17','greeting');
 const [comparison,setComparison]=useShoppingState<string[]>('stylist-18',[]);
 const last=transcript.filter(x=>x.who==='stylist').at(-1)?.text||greeting;const voice=useStylistVoice(respond);

 function answer(message:string,next:string[],speech:StylistSpeechKey){setTranscript(t=>[...t,{who:'stylist',text:message}]);setChoices(next);setLastSpeech(speech);voice.say(speech,true)}
 function updateProfile(next:Brief){
  voice.stop();const hasContext=!!(next.occasion||next.category);setCardPage(0);setLastSpeech(hasContext?'results':'occasion');setBrief(next);setMode('discover');setPieces(hasContext||next.wardrobe?selectPieces(products,next):[]);setOffset(0);
  const message=next.wardrobe?(hasContext?'I’ve refreshed your edit using the details you shared, keeping your budget and comfort preferences. Would you like to compare or keep exploring?':'Let’s build from the details you shared. What would you like to add—a jacket, a top, or shoes?'):hasContext?'I’ve refreshed your edit with these preferences. What would you like to refine next?':(next.presentation?next.presentation+' it is. ':'')+'What are we dressing for?';
  setTranscript(t=>[...t,{who:'stylist',text:message}]);setChoices(hasContext?['Compare these two','Build a look with the first','Show other options','More affordable']:next.wardrobe?['A jacket','A top','Shoes']:['A wedding','Work','A getaway','Everyday']);
 }


 function startConversation(){setStarted(true);voice.startConversation(lastSpeech)}
 function respond(value:string){if(!value.trim())return;setStarted(true);setText('');setCardPage(0);setTranscript(t=>[...t,{who:'you',text:value}]);const raw=value.toLowerCase();const s=/^(yes|yes please|sure|go ahead|okay|ok)[.!?]*$/.test(raw.trim())&&pieces.length?(lastSpeech==='compare'?'build a look with the first':pieces.length>1?'compare these two':'build a look with the first'):raw;
 if(/start (over|again)|reset/.test(s)){setBrief({...emptyBrief,wardrobe:wardrobeContext(notes,wardrobeEntries)});setPieces([]);setMobileView('talk');setMode('discover');setOffset(0);answer('A fresh start. Which style direction would you like to explore?',['Feminine','Masculine','A mix'],'reset');return}
 if(/compare|side.by.side|two looks/.test(s)&&pieces.length>=2){setComparison(pieces.slice(0,2).map(p=>p.id));setMode('compare');setMobileView('edit');answer('Let’s put these first two pieces side by side. With your profile saved, you’ll see them on you. Which one feels more like you?',['Build a look with the first','Build a look with the second','Show other options'],'compare');return}
 if(/complete|put.*look|build.*look|finish.*look/.test(s)&&pieces.length){const p=/second/.test(s)?pieces[1]||pieces[0]:pieces[0];setAnchor(p);setMode('outfit');setMobileView('edit');answer('Let’s build around '+p.name+'. I’ve added complementary categories from the same collection. You can swap any piece, choose sizes, and add the look to your demo bag.',['Compare these two','Show other options','Start over'],'build');return}
 const next=understand(value,brief);if(/cheaper|less expensive|more affordable/.test(s)&&brief.budget===null&&pieces.some(p=>p.currency==='USD'&&p.price>0))next.budget=Math.max(1,Math.floor(Math.min(...pieces.filter(p=>p.currency==='USD'&&p.price>0).map(p=>p.price))*.8));setBrief(next);setMode('discover');setMobileView('talk');
 if(next.occasion){setPieces(selectPieces(products,next,0));setOffset(0)}
 if(/fit|too tight|too loose|size/.test(s)&&!next.occasion&&!next.category){answer('We can explore your recommended size and compare fit previews once you pick a piece. First, what are you shopping for?',['Work','A wedding','Everyday'],'occasion');return}
 if(!next.occasion&&!next.category){answer('Tell me the occasion first—perhaps a wedding, dinner, work, or a getaway?',['A wedding','An evening out','Work','A getaway'],'occasion');return}
 if(!next.direction&&!next.category){answer(next.occasion==='A wedding'?'Lovely. What’s the dress code or mood—formal, understated, or a statement look?':'What feels right for you—relaxed, understated, or a little more of a statement?',['Formal','Understated','Statement','Relaxed'],next.occasion==='A wedding'?'wedding':'mood');return}
 if(!next.category){answer('Would you like to explore dresses, tailored separates, or just the finishing accessories?',next.presentation==='Masculine'?['Tailored separates','Accessories','Dresses']:['Dresses','Tailored separates','Accessories'],'category');return}
 const more=/other|more options|something else|don't like|don’t like|not (?:these|my style)/.test(s);const newOffset=more?offset+4:0;let found=selectPieces(products,next,newOffset);if(!found.length&&more)found=selectPieces(products,next,0);setOffset(found.length&&more?newOffset:0);setPieces(found);setMobileView(found.length?'edit':'talk');
 if(!found.length){answer('Nothing in this collection matches all those preferences yet. I’ll keep your exclusions. Would you like a different category or a higher budget?',['No budget limit','Dresses','Tailored separates','Start over'],'empty');return}
 const prefix=tone==='advisor'?'I have a few ideas for you. ':tone==='editorial'?'Let’s give this look a point of view. ':'Here’s a considered starting point. ';
 answer(prefix+reasonFor(found[0],next)+' These pieces are from the store’s collection'+(next.budget!==null?`, each under $${next.budget}. `:'. ')+(found.length>1?'Would you like to compare the first two on you, or build a complete look?':'Shall we build a complete look around this piece?'),[...(found.length>1?['Compare these two']:[]),'Build a look with the first','Show other options','More affordable'],found.length>1?'results':'single');
 }
 const shown=pieces.slice(cardPage*2,cardPage*2+2),history=transcript.slice(historyPage*2,historyPage*2+2);
 return <div className="voice-stylist stylist-desktop" data-mobile-view={mobileView}>
 <header className="stylist-bar"><div><p className="eyebrow">SPREEAI · PERSONAL STYLIST</p><h2>Chat with a stylist.</h2><p className="stylist-task-summary">Type your occasion, mood or budget. We’ll suggest pieces to explore.</p></div><nav aria-label="Stylist tools"><button className="stylist-mute" aria-label={voice.muted?'Turn stylist sound on':'Mute stylist sound'} aria-pressed={voice.muted} onClick={()=>voice.setMuted(!voice.muted)}>{voice.muted?<SpeakerSlash size={17}/>:<SpeakerHigh size={17}/>}<span>{voice.muted?'Sound off':'Sound on'}</span></button><button title="Add notes about pieces you own" onClick={()=>{voice.stop();setPanel('wardrobe')}}>My wardrobe</button><button title="Choose and preview the stylist voice" onClick={()=>setPanel('voice')}>Voice</button><button title="Review this session’s conversation" onClick={()=>{setHistoryPage(Math.max(0,Math.ceil(transcript.length/2)-1));setPanel('history')}}>History</button></nav></header>
 <div className="stylist-preferences"><div className="stylist-direction-pills" aria-label="Style direction">{(['Feminine','Masculine','A mix'] as const).map(p=><button key={p} aria-pressed={brief.presentation===p} onClick={()=>updateProfile({...brief,presentation:p})}>{p}</button>)}</div><label>Budget per piece<select aria-label="Stylist budget" value={brief.budget??''} onChange={e=>updateProfile({...brief,budget:e.target.value?Number(e.target.value):null})}><option value="">Flexible</option><option value="250">Under $250</option><option value="500">Under $500</option><option value="1000">Under $1,000</option><option value="2500">Under $2,500</option>{brief.budget!==null&&![250,500,1000,2500].includes(brief.budget)&&<option value={brief.budget}>Under ${brief.budget}</option>}</select></label><button className="stylist-reset" onClick={()=>respond('Start over')}>Start fresh</button></div>
 <div className="voice-mobile-tabs" aria-label="Stylist views"><button aria-pressed={mobileView==='talk'} onClick={()=>setMobileView('talk')}>Conversation</button><button aria-pressed={mobileView==='edit'} onClick={()=>setMobileView('edit')}>Your edit {pieces.length||''}</button></div>
 <div className="stylist-stage"><section className="stylist-talk"><div className="stylist-presence"><div className={'voice-orb '+(voice.speaking?'is-speaking':voice.listening?'is-listening':'')} aria-hidden="true"><Waveform size={28}/></div><div><strong>Celine</strong><span>{voice.connecting?'Connecting microphone…':voice.listening?'Listening to you':voice.speaking?'Speaking':voice.muted?'Sound off · Type or tap to continue':'Your personal stylist · Recorded voice'}</span></div><button className="stylist-audio" disabled={voice.muted} aria-label={voice.speaking?'Stop speaking':'Hear stylist reply'} onClick={()=>voice.speaking?voice.stop():voice.say(lastSpeech,true)}>{voice.speaking?<Stop size={20}/>:<SpeakerHigh size={20}/>}</button></div>
 <div className="stylist-reply-area"><p className="stylist-last" aria-live="polite">{last}</p>{voice.heard&&<p className="stylist-heard">You: {voice.heard}</p>}{voice.issue&&<p className="stylist-voice-error" role="status">{voice.issue}</p>}</div>
 <div className="stylist-next"><small>TAKE IT FROM HERE</small><div className="voice-suggestions">{choices.filter(choice=>!['Feminine','Masculine','A mix'].includes(choice)).map(c=><button key={c} onClick={()=>respond(c)}>{c}</button>)}</div></div>
 <div className="stylist-input-area"><button className="voice-start" onClick={!started?startConversation:voice.listen}><Microphone size={18}/>{!started?'Start conversation':voice.connecting?'Cancel microphone':voice.listening?'Done speaking':'Tap to speak'}</button>{voice.active&&<button className="stylist-stop" onClick={voice.stop}>End voice</button>}<form className="voice-reply" onSubmit={e=>{e.preventDefault();respond(text)}}><input aria-label="Reply to your stylist" value={text} onChange={e=>setText(e.target.value)} maxLength={500} placeholder="Tell me what you have in mind…"/><button aria-label="Send reply" disabled={!text.trim()}><PaperPlaneTilt size={18}/></button></form><p>Speak or type. Add details like “no heels” or “relaxed.”</p></div></section>
 <section className="stylist-edit"><div className="stylist-edit-heading"><div><p className="eyebrow">CURATED WITH YOU</p><h3>{pieces.length?'Your next possibilities.':'A little inspiration.'}</h3></div>{pieces.length>0&&<span>{cardPage*2+1}–{Math.min(cardPage*2+2,pieces.length)} / {pieces.length}</span>}</div><div className="stylist-brief-line">{[brief.presentation,brief.occasion,brief.direction,...(brief.preferences||[]),...brief.avoid.map(v=>'No '+v)].filter(Boolean).filter((v,i,a)=>a.findIndex(x=>x.toLowerCase()===v.toLowerCase())===i).join(' · ')||'Your plans. Your comfort. Your point of view.'}</div>
 <div className="stylist-card-pair">{(pieces.length?shown:selectPieces(products,brief).slice(0,2)).map(p=><article key={p.id}><Link onClick={onProduct} to={`/product/${p.id}`} className="stylist-card-photo"><img src={p.image} alt={p.name}/></Link><div className="stylist-card-copy"><small>{p.category}</small><Link onClick={onProduct} to={`/product/${p.id}`}><h4>{p.name}</h4></Link><p>{p.priceLabel}</p>{pieces.length>0&&<button onClick={()=>{setAnchor(p);setMode('outfit');voice.stop()}}>Build this look</button>}</div></article>)}</div>
 <div className="stylist-edit-actions">{pieces.length>1&&<button onClick={()=>{setComparison(shown.map(p=>p.id));setMode('compare');voice.stop()}}>Compare on you</button>}{pieces.length>2&&<div><button aria-label="Previous stylist pieces" disabled={cardPage===0} onClick={()=>setCardPage(n=>n-1)}>←</button><button aria-label="Next stylist pieces" disabled={(cardPage+1)*2>=pieces.length} onClick={()=>setCardPage(n=>n+1)}>→</button></div>}</div><p className="stylist-fine">Product photography shown · Choose Compare on you or Build this look for personal previews</p></section></div>
 <Dialog.Root open={!!panel} onOpenChange={v=>{if(!v)setPanel(null)}}><Dialog.Portal><Dialog.Overlay className="stylist-sheet-overlay"/><Dialog.Content className="stylist-sheet"><header><Dialog.Title>{panel==='wardrobe'?'A little more you.':panel==='history'?'Our conversation.':'The voice of your stylist.'}</Dialog.Title><Dialog.Close aria-label="Close stylist tools">×</Dialog.Close></header><Dialog.Description className="sr-only">{panel==='wardrobe'?'Share wardrobe notes for this session.':panel==='history'?'Review your conversation one page at a time.':'Preview the recorded Celine voice.'}</Dialog.Description>
 {panel==='wardrobe'?<WardrobePanel notes={notes} entries={wardrobeEntries} onApply={(newNotes,entries)=>{setNotes(newNotes);setWardrobeEntries(entries);updateProfile({...brief,wardrobe:wardrobeContext(newNotes,entries)})}}/>:panel==='history'?<div className="stylist-history"><div>{history.map((m,i)=><p key={i}><strong>{m.who==='you'?'You':'Celine'}</strong>{m.text}</p>)}</div><nav><button disabled={historyPage===0} onClick={()=>setHistoryPage(n=>n-1)}>← Previous</button><span>{historyPage+1} / {Math.ceil(transcript.length/2)}</span><button disabled={(historyPage+1)*2>=transcript.length} onClick={()=>setHistoryPage(n=>n+1)}>Next →</button></nav></div>:<div className="stylist-voices"><p>Natural recorded guidance from Celine. Detailed personal recommendations stay on screen.</p>{personalities.map(p=><button key={p.id} aria-pressed={tone===p.id} onClick={()=>{setTone(p.id);voice.say(p.id as StylistSpeechKey,true)}}><strong>{p.name}</strong><span>{p.detail}</span><SpeakerHigh size={18}/></button>)}<button onClick={voice.stop}>Stop preview</button></div>}</Dialog.Content></Dialog.Portal></Dialog.Root>
 <Dialog.Root open={mode!=='discover'} onOpenChange={v=>{if(!v)setMode('discover')}}><Dialog.Portal><Dialog.Overlay className="overlay"/><Dialog.Content className="modal wide stylist-look-workspace" aria-describedby="stylist-look-description"><Dialog.Title className="sr-only">{mode==='compare'?'Compare your looks':'Build your look'}</Dialog.Title><Dialog.Description className="sr-only" id="stylist-look-description">Explore your selected pieces. Close to return to your stylist.</Dialog.Description><Dialog.Close className="close" aria-label="Return to stylist">×</Dialog.Close>{mode==='compare'?<CompareLooks key={comparison.join('|')} initial={comparison}/>:anchor&&<CompleteLook key={anchor.id} product={anchor} initialProducts={completePieces(products,anchor,brief)} onBag={onBag}/>}</Dialog.Content></Dialog.Portal></Dialog.Root>
 </div>
}
