import {useState} from 'react';
import {EnvelopeSimple} from '@phosphor-icons/react/dist/csr/EnvelopeSimple';
import {InstagramLogo} from '@phosphor-icons/react/dist/csr/InstagramLogo';
import {PinterestLogo} from '@phosphor-icons/react/dist/csr/PinterestLogo';
import {ShoppingBag} from '@phosphor-icons/react/dist/csr/ShoppingBag';
import {reviewWardrobeText,type WardrobeEntry,type WardrobeSource} from './stylist-wardrobe';
const sources=[
 {id:'gmail',name:'Gmail purchases',Icon:EnvelopeSimple,detail:'Order confirmations and receipts',help:'Gmail sign-in is not connected in this demo. Paste clothing purchase lines from a receipt below. You’ll review every item before the stylist uses it.'},
 {id:'pinterest',name:'Pinterest inspiration',Icon:PinterestLogo,detail:'Colors, shapes and saved looks',help:'Pinterest sign-in is not connected in this demo. Describe the clothing, colors or fabrics from a saved board below. Links alone cannot be read.'},
 {id:'instagram',name:'Instagram inspiration',Icon:InstagramLogo,detail:'Outfits and styling you love',help:'Instagram import is not connected in this demo. Describe what you like about an outfit below. We cannot read your feed, saved posts or a link.'},
 {id:'retailer',name:'Previous purchases',Icon:ShoppingBag,detail:'Pieces you already own',help:'Retailer accounts are not connected in this demo. Add the clothing items you already own, one per line.'},
] as const;
export default function WardrobePanel({notes,entries,onApply}:{notes:string;entries:WardrobeEntry[];onApply:(notes:string,entries:WardrobeEntry[])=>void}){
 const [source,setSource]=useState<WardrobeSource|null>(null),[draft,setDraft]=useState(''),[review,setReview]=useState<WardrobeEntry[]|null>(null),[selected,setSelected]=useState<string[]>([]),[consent,setConsent]=useState(false),[draftNotes,setDraftNotes]=useState(notes),[message,setMessage]=useState('');
 const provider=sources.find(p=>p.id===source);
 function reset(){setSource(null);setDraft('');setReview(null);setSelected([]);setConsent(false);setMessage('')}
 function apply(){const next=[...entries,...(review||[]).filter(e=>selected.includes(e.id)&&!entries.some(old=>old.source===e.source&&old.text.toLowerCase()===e.text.toLowerCase()))].slice(0,40);onApply(notes,next);reset();setMessage('Added to this conversation. Your stylist will use these details.')}
 return <div className="wardrobe-panel">{!source?<>
 <p>Build around what you own and the looks you love. You choose what your stylist learns.</p>
 <div className="wardrobe-source-grid">{sources.map(({id,name,Icon,detail})=><button key={id} onClick={()=>{reset();setSource(id)}}><Icon size={22}/><strong>{name}</strong><span>{detail}</span><small>Add manually · Sign-in not connected</small></button>)}</div>
 <label className="wardrobe-notes-label">Comfort, colors & preferences<textarea aria-label="Wardrobe notes" maxLength={1200} value={draftNotes} onChange={e=>{setDraftNotes(e.target.value);setConsent(false)}} placeholder="No wool. I prefer relaxed fits and navy. I already own white sneakers."/></label>
 <label className="wardrobe-permission"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/>Use these notes in this stylist conversation.</label>
 <button className="wardrobe-primary" disabled={!consent||!draftNotes.trim()} onClick={()=>{onApply(draftNotes.trim(),entries);setMessage('Your preferences are now part of this conversation.')}}>Use my preferences</button>
 {entries.length>0&&<section className="wardrobe-approved"><h3>What you’ve shared · {entries.length}</h3>{entries.map(e=><div key={e.id}><span>{e.text}<small>{e.kind==='owned'?'Owned piece':'Inspiration'} · Added manually</small></span><button aria-label={`Remove ${e.text}`} onClick={()=>onApply(notes,entries.filter(x=>x.id!==e.id))}>×</button></div>)}</section>}
 {(entries.length>0||notes)&&<button className="wardrobe-clear" onClick={()=>{setDraftNotes('');setConsent(false);onApply('',[]);setMessage('Wardrobe details cleared.')}}>Clear all wardrobe details</button>}
 </>:<><button className="wardrobe-back" onClick={reset}>Back to my wardrobe</button><h3>{provider?.name}</h3><p>{provider?.help}</p>{review===null?<><label className="wardrobe-notes-label">{source==='gmail'||source==='retailer'?'Clothing purchase details':'What you like about these looks'}<textarea aria-label="Details to review" value={draft} maxLength={8000} onChange={e=>setDraft(e.target.value)} placeholder={source==='gmail'||source==='retailer'?'Navy tailored trousers\nWhite leather sneakers':'Relaxed linen shirts\nNeutral tailoring with navy accents'}/></label><p className="wardrobe-note">Leave out addresses, payment details and order numbers. Nothing is fetched from an account.</p><button className="wardrobe-primary" disabled={!draft.trim()} onClick={()=>{const rows=reviewWardrobeText(draft,source);setReview(rows);setSelected(rows.map(r=>r.id));setConsent(false);setDraft('')}}>Review items</button></>:<><h4>Choose what your stylist can use</h4>{!review.length?<p>No clothing details found. Go back and add a garment, fabric or style description.</p>:<div className="wardrobe-review">{review.map(e=><label key={e.id}><input type="checkbox" checked={selected.includes(e.id)} onChange={event=>setSelected(old=>event.target.checked?[...old,e.id]:old.filter(x=>x!==e.id))}/><span>{e.text}<small>{e.kind==='owned'?'I already own this':'Style inspiration'}</small></span></label>)}</div>}<label className="wardrobe-permission"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/>Use only the selected details in this conversation.</label><button className="wardrobe-primary" disabled={!consent||!selected.length} onClick={apply}>Add {selected.length} {selected.length===1?'item':'items'} to my wardrobe</button><button className="wardrobe-back" onClick={()=>{setReview(null);setConsent(false)}}>Edit details</button></>}</>}
 {message&&<p role="status" className="wardrobe-notice">{message}</p>}<p className="wardrobe-note">Shared details stay in this open stylist session and clear when it closes. Account imports need a separate, approved connection.</p>
 </div>;
}
