import ExperienceWelcome from '../ExperienceWelcome';
const BASE='/spreeai-always-on-demo/';
export default function AssociateWelcome({vic,open,onClose,onStart}:{vic:boolean;open:boolean;onClose:()=>void;onStart:()=>void}){

 const steps=[
 {label:'Meet your client',title:vic?'A familiar face.\nA personal approach.':'Start with them.\nMake it personal.',body:(vic?'For store associates and independent personal stylists. ':'A workspace for helping customers in the store. ')+'Find a saved client, import a contact, or create a new profile. Add an approved photo or Twin when you’re ready. No customer sign-in needed.',detail:'Add measurements and style notes. Your client book stays in this browser and is shared between In-Store and VIC.',cue:'01 / THE CLIENT',image:BASE+`associate/assets/walkthrough/${vic?'vic-client':'in-store-client'}.webp`,alt:vic?'Freja reviewing a client profile on a tablet':'Malik reviewing a tablet in a boutique'},
 {label:'Curate their looks',title:'Real pieces.\nTheir possibilities.',body:'Explore the collection, build an outfit, and create a personal preview. Change a selected size to see that piece’s fit update in the preview.',detail:'Save up to five named looks per client, each with its own pieces, sizes, and preview. Twins provide illustrative previews and starting sizes.',cue:'02 / THE PERSONAL EDIT',image:BASE+`associate/assets/walkthrough/${vic?'vic-curation.webp':'in-store-curation-cardigan.png'}`,alt:vic?'Freja curating an outfit':'Malik selecting garments from a boutique clothing rail'},
 {label:vic?'Make it a conversation':'Prepare their fitting',title:vic?'A thoughtful edit.\nReady to share.':'From a preview.\nTo the fitting room.',body:vic?'Open a saved look, review the image and size notes, and make the message sound like you. Share the image and message through your device’s messaging app.':'Show the look on your phone or tablet, confirm the selected sizes, and mark the pieces you’ve prepared. Copy the fitting edit for your handoff.',detail:vic?'You review and send. If image sharing is unavailable, download the preview and attach it with your message. The demo does not send texts automatically.':'The fitting checklist helps organize the visit. Stock, reservations, and checkout are not connected in this demo.',cue:vic?'03 / THE CONVERSATION':'03 / THE IN-PERSON MOMENT',image:BASE+`associate/assets/walkthrough/${vic?'vic-message':'in-store-fitting'}.webp`,alt:vic?'Freja preparing a personal message on her phone':'Malik reviewing a jacket in a fitting suite'}
 ];
 return <ExperienceWelcome channel={vic?'VIC Clienteling':'In-Store'} audience="For associates & personal stylists" steps={steps} open={open} onClose={onClose} onStart={onStart} startLabel="Open my client book" footer="Replay this introduction anytime from How it works."/>;
}
