import {useEffect,useState} from 'react';
import {AddressBook} from '@phosphor-icons/react/dist/csr/AddressBook';
import {UserPlus} from '@phosphor-icons/react/dist/csr/UserPlus';
import {searchClients,type ClientRecord} from './client-book';
import ContactImport from './ContactImport';
import {sourceLabel,type ContactDraft} from './contact-import';
function ClientPhoto({client}:{client:ClientRecord}){const [url,setUrl]=useState('');useEffect(()=>{if(!client.photo)return;const src=URL.createObjectURL(client.photo);setUrl(src);return()=>URL.revokeObjectURL(src)},[client.photo]);return url?<img src={url} alt={`${client.name}’s saved photo`}/>:<span className="as-client-initial">{client.name.trim().slice(0,1).toUpperCase()}</span>}
export default function ClientBook({clients,onOpen,onNew,onDelete,onImport,busy}:{clients:ClientRecord[];onOpen:(c:ClientRecord)=>void;onNew:()=>void;onDelete:(c:ClientRecord)=>void;onImport:(draft:ContactDraft)=>Promise<void>;busy:boolean}){
 const [query,setQuery]=useState(''),[remove,setRemove]=useState(''),[importing,setImporting]=useState(false),[notice,setNotice]=useState('');const rows=searchClients(clients,query);
 return <div className="as-client-book">{!importing&&<><p className="as-eyebrow">RELATIONSHIPS, REMEMBERED</p><h2>Your client book.</h2><p>One place for the people you style—in store or independently.</p><div className="as-book-source"><strong>Your clients, added by you.</strong><p>This list contains profiles you save here. It doesn’t search your phone book or a retailer’s customer database.</p><span>On this browser · Shared between In-Store and VIC</span></div></>}
 {importing?<ContactImport clients={clients} onOpen={onOpen} onCancel={()=>setImporting(false)} onSave={async draft=>{await onImport(draft);setQuery('');setImporting(false);setNotice(`${draft.name} added. Add a photo or Twin whenever you’re ready.`)}}/>:<><div className="as-book-actions"><button className="as-primary" disabled={busy} onClick={()=>{setNotice('');setImporting(true)}}><AddressBook size={21}/>Import contact</button><button className="as-secondary" disabled={busy} onClick={onNew}><UserPlus size={21}/>Create client profile</button></div><div className="as-book-tools"><label>Search saved clients<input type="search" placeholder="Name, email, phone or style notes" value={query} onChange={e=>setQuery(e.target.value)}/></label></div></>}
 {notice&&<p className="as-contact-notice" role="status">{notice}</p>}{!importing&&<><div className="as-client-list">{rows.map(c=><article key={c.id}><ClientPhoto client={c}/><div><h3>{c.name}</h3><p>{c.phone||c.email||'Contact saved'}</p><small>{sourceLabel(c.contactSource)} · {c.identity?`${c.looks.length}/5 looks`:'Ready for a personal profile'}</small><button className="as-text" disabled={busy} onClick={()=>onOpen(c)}>{c.identity?`Open ${c.name}`:'Add photo or Twin'}</button></div><button className="as-text" disabled={busy} aria-label={`Remove ${c.name} from client book`} onClick={()=>setRemove(c.id)}>Remove</button>{remove===c.id&&<div className="as-client-remove"><p>Remove this saved profile, photo, and all its looks from this browser?</p><button className="as-secondary" onClick={()=>setRemove('')}>Keep client</button><button className="as-primary" disabled={busy} onClick={()=>{onDelete(c);setRemove('')}}>Remove saved client</button></div>}</article>)}</div>{!rows.length&&<p className="as-book-empty">{query?'No saved clients match. Import a contact or create a new profile above.':'Start with a contact you know, or create a new client profile.'}</p>}</>}
 <p className="as-fine as-book-storage">Use your own or a trusted work device. This demo doesn’t sync across devices. Clearing browser data removes the client book.</p></div>
}
