import useMeasurementJump from '../useMeasurementJump';
import {useEffect,useState} from 'react';
import ClientPhoto from './ClientPhoto';
import {listTwins,avatarIdentity,uploadPhoto,saveMeasurements,useConnectedProfile,type Avatar,type Identity} from '../connection';
export default function ClientProfile({name,setName,onDone,onSearch,emailValue,phoneValue,notesValue,setEmailValue,setPhoneValue,setNotesValue}:{onSearch:()=>void;name:string;setName:(s:string)=>void;onDone:(identity:Identity,photo?:Blob)=>Promise<void>;emailValue:string;phoneValue:string;notesValue:string;setEmailValue:(s:string)=>void;setPhoneValue:(s:string)=>void;setNotesValue:(s:string)=>void}){
 const {measurementsRef,jumpToMeasurements}=useMeasurementJump();
 const profile=useConnectedProfile();const [method,setMethod]=useState<'twin'|'photo'>(profile.identity?.kind||'photo'),[twins,setTwins]=useState<Avatar[]>([]),[choice,setChoice]=useState<Identity|null>(profile.identity),[height,setHeight]=useState(profile.identity?.height||170),[weight,setWeight]=useState(profile.identity?.weight||65),[body,setBody]=useState<'Feminine'|'Masculine'>(profile.identity?.bodyType||'Feminine'),[file,setFile]=useState<File|null>(null),[preview,setPreview]=useState(''),[consent,setConsent]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[loading,setLoading]=useState(true);
 function load(){setLoading(true);setError('');listTwins().then(setTwins).catch(e=>setError(e.message)).finally(()=>setLoading(false))}
 useEffect(load,[]);useEffect(()=>{if(!file){setPreview('');return}const url=URL.createObjectURL(file);setPreview(url);return()=>URL.revokeObjectURL(url)},[file]);
 function choose(t:Identity){setChoice(t);setFile(null);setHeight(t.height);setWeight(t.weight);setBody(t.bodyType);jumpToMeasurements()}
 async function run(fn:()=>Promise<void>){setBusy(true);setError('');try{await fn()}catch(e){setError(e instanceof Error?e.message:'Please try again.')}finally{setBusy(false)}}
 return <div className="as-profile"><p className="as-eyebrow">A PERSONAL START</p><h2>Meet your client.</h2><p>For a store visit or your independent styling practice. Add their details, then choose how to preview their look.</p><div className="as-client-entry"><button className="as-secondary" onClick={onSearch}>Client book / import contact</button><span aria-current="step">Add or update client</span></div><label>Client name<input value={name} onChange={e=>setName(e.target.value)} maxLength={100} placeholder="Full name"/></label><div className="as-form-row"><label>Email · optional<input type="email" value={emailValue} onChange={e=>setEmailValue(e.target.value)} placeholder="Client email"/></label><label>Mobile · optional<input type="tel" value={phoneValue} onChange={e=>setPhoneValue(e.target.value)} placeholder="Include country code"/></label><label>Style notes · optional<input value={notesValue} maxLength={500} onChange={e=>setNotesValue(e.target.value)} placeholder="Preferences, occasions…"/></label></div><p className="as-fine">Save this profile and its approved photo in the client book on this browser.</p><div className="as-methods">{[['photo','Take or upload photo'],['twin','Use a Twin']].map(([id,label])=><button key={id} aria-pressed={method===id} onClick={()=>{setMethod(id as typeof method);setError('')}}>{label}</button>)}</div>
 {method==='photo'?<div className="as-photo-upload">{preview&&<img src={preview} alt="Client photo to review"/>}<ClientPhoto onPhoto={f=>{if(f.size>8*1024*1024||!['image/jpeg','image/png','image/webp'].includes(f.type)){setError('Choose a JPG, PNG, or WebP under 8 MB.');return}setError('');setFile(f);setChoice(null);setConsent(false)}}/><p>Use a clear, full-body photo in fitted clothing. The photo is uploaded to SPREEAI when you save.</p></div>:<><div className="as-twins">{twins.map(t=><button key={t.id} aria-pressed={choice?.id===t.id} onClick={()=>choose(avatarIdentity(t))}><img loading="lazy" src={t.url} alt={t.name}/><strong>{t.name}</strong><small>{Math.round(t.user_height_centimeters)} cm · {Math.round(t.user_weight_kilograms)} kg</small></button>)}</div>{loading&&<p role="status">Loading Twins…</p>}{!loading&&!twins.length&&<button onClick={load}>Retry Twins</button>}</>}
 {(file||choice?.kind==='photo')&&<label className="as-check"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/>The client is 18 or older and has approved saving this photo and using it for try-on.</label>}
 <form className="as-measures" onSubmit={e=>{e.preventDefault();void run(async()=>{if(!name.trim())throw Error('Enter the client’s name to save their profile.');if((file||choice?.kind==='photo')&&!consent)throw Error('Confirm the client’s permission first.');let selected=choice;if(file){const result=await uploadPhoto(file);selected={...result,name:name||'Client',kind:'photo',height,weight,bodyType:body}}if(!selected)throw Error('Choose a photo or Twin.');const identity={...selected,height,weight,bodyType:body};await saveMeasurements(identity);await onDone(identity,file||undefined)})}}>{choice&&<p className="as-selection-note">Selected: {choice.name}{choice.kind==='twin'?' · Twin':''}</p>}<div ref={measurementsRef} className="as-form-row measurement-fields" tabIndex={-1} role="group" aria-label="Height, weight, and sizing profile"><label>Height · cm<input required type="number" step="any" min="100" max="230" value={height} onChange={e=>setHeight(Number(e.target.value))}/></label><label>Weight · kg<input required type="number" step="any" min="30" max="250" value={weight} onChange={e=>setWeight(Number(e.target.value))}/></label><label>Sizing profile<select value={body} onChange={e=>setBody(e.target.value as typeof body)}><option>Feminine</option><option>Masculine</option></select></label></div><p className="as-fine">An Twin is an illustrative stand-in. Its starting sizes are not the client’s personal fit.</p><button className="as-primary" disabled={busy}>{busy?'Saving client…':'Save to client book'}</button></form>{error&&<p className="as-error" role="alert">{error}</p>}</div>
}
